### ISSUE TITLE
Why SSR pages rerender on client side?

### ISSUE THREAD

**Issue by saffari-m** [isomorphic-microfrontends/pokemons#5]
Hi.

After page rendered as a SSR  and it receive on user browser, `/pokemons page` rerender on client side. why it's happening?
Do you have any solution?

@tsukhu

**Comment by internettrans** [comment]
The initial page is rendered on the server side, and subsequent pages are rendered client side. It's happening because that's how React Router works - it performs client side navigation.

**Comment by saffari-m** [comment]
Thanks @joeldenning for your respond.

But i'm confuse about this action! I saw in `isomorphic-microfrontends` and it's demo [`isomorphic.microfrontends.app`](https://isomorphic.microfrontends.app/pokemons). 
when we send request for page : `/pokemons`  as you said it's response have rendered data but after few second this page render on client side and fetch again pokemons list api.
I need prevent rerender page in this situation. it's possible?

**Comment by internettrans** [comment]
You can pass data from server to client via the single-spa-layout props.
